### PR TITLE
Update ssn_high_group_code_loader.rb

### PR DESCRIPTION
**Pull request by jdashton**
Modify date-matching regex to handle dates without a leading zero.

Is it still necessary or useful to run the high_group_loader rake task, since the SSA has implemented randomized assignment?  If yes, it looks like their website started documenting dates with no leading zero in January of '07, like 1/03/07.  The single-character change in this pull request handles that case.

If no longer necessary, perhaps it would be good to update the README.

Thanks!

### CODE REVIEW

**Comment by kevintyll** [comment]
We have since stopped running the rake task.  I've updated the README as you suggested. Thanks.

**Comment by jdashton** [comment]
Hoping this reaches you.  With the randomized assignment, does it make 
sense to carve out the parts of this gem that depend on a high-groups 
table?  If a given project (such as mine) doesn't plan to use death 
tapes, could the gem be made to function without any migration?

On 10/11/13 8:49 AM, Kevin Tyll wrote:

> We have since stopped running the rake task. I've updated the README 
> as you suggested. Thanks.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/kevintyll/ssn_validator/pull/2#issuecomment-26134348.

## 

Daniel Ashton      PGP key available     http://Daniel.AshtonFam.org
mailto:Daniel@AshtonFam.org           http://ChamberMusicWeekend.org
  AIM: FirstFiddl           ICQ# 9445142           http://MDMusic.org

**Comment by kevintyll** [comment]
I'm not sure what you're asking.  I think the gem is really only useful now for determining if the ssn belongs on the DMF.  Everything not DMF related could probably just be removed from the gem.

Kevin Tyll
kevintyll@gmail.com

**Comment by jdashton** [comment]
Thanks for writing back.  :-)  Before I found your gem I knew there were 
certain things that could be checked even without the high-groups.  Area 
666 and 000, group 00 and serial 0000 are all obvious hits.  Any area 
that begins with 9 is still invalid.

In addition, I know there are some otherwise believable numbers that are 
invalid.  Your gem seems to be catching 123-45-6789, which is not on any 
of the invalid lists I've seen yet.

So it seems like there may be some usefulness left in your gem, even for 
those who haven't subscribed to the DMF tapes.

Am I missing my guess with any of the above?

If you /are/ already doing checks like those above (and perhaps more), 
then carving out the old high-groups tests could make today's gem more 
accurate and easier to use, since at least one of the tables is no 
longer useful.

In future work, I can imagine your gem being extended to interface with 
the SSA's free employability check in some manner, yet to be determined.

What do you think?

On 10/11/13 12:33 PM, Kevin Tyll wrote:

> I'm not sure what you're asking. I think the gem is really only useful 
> now for determining if the ssn belongs on the DMF. Everything not DMF 
> related could probably just be removed from the gem.
> 
> Kevin Tyll
> kevintyll@gmail.com
> 
> On Oct 11, 2013, at 11:47 AM, jdashton notifications@github.com wrote:
> 
> > Hoping this reaches you. With the randomized assignment, does it make
> > sense to carve out the parts of this gem that depend on a high-groups
> > table? If a given project (such as mine) doesn't plan to use death
> > tapes, could the gem be made to function without any migration?
> > 
> > On 10/11/13 8:49 AM, Kevin Tyll wrote:
> > 
> > > We have since stopped running the rake task. I've updated the README
> > > as you suggested. Thanks.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> > > https://github.com/kevintyll/ssn_validator/pull/2#issuecomment-26134348.
> > 
> > ## 
> > 
> > Daniel Ashton PGP key available http://Daniel.AshtonFam.org
> > mailto:Daniel@AshtonFam.org http://ChamberMusicWeekend.org
> > AIM: FirstFiddl ICQ# 9445142 http://MDMusic.org
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/kevintyll/ssn_validator/pull/2#issuecomment-26151370.

## 

Daniel Ashton      PGP key available     http://Daniel.AshtonFam.org
mailto:Daniel@AshtonFam.org           http://ChamberMusicWeekend.org
  AIM: FirstFiddl           ICQ# 9445142           http://MDMusic.org

**Comment by kevintyll** [comment]
The problem is, if SSNs are now generated randomly, or at least with an unpublished algorithm, how do we know that 123-45-6789, or any other number is still invalid?

Kevin Tyll
kevintyll@gmail.com

**Pull request closed without merging**
